// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parkyou.Data;

namespace Parkyou.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210525232634_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("Name")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Parkyou.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LastName");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Rol");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Parkyou.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(127)
                        .HasColumnType("int");

                    b.Property<int>("Col")
                        .HasColumnType("int")
                        .HasColumnName("Col");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Row");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("parking_spots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Col = 1,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 2,
                            Col = 2,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 3,
                            Col = 3,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 4,
                            Col = 4,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 5,
                            Col = 5,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 6,
                            Col = 6,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 7,
                            Col = 7,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 8,
                            Col = 8,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 9,
                            Col = 9,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 10,
                            Col = 10,
                            Row = "A",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 11,
                            Col = 1,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 12,
                            Col = 2,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 13,
                            Col = 3,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 14,
                            Col = 4,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 15,
                            Col = 5,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 16,
                            Col = 6,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 17,
                            Col = 7,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 18,
                            Col = 8,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 19,
                            Col = 9,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 20,
                            Col = 10,
                            Row = "B",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 21,
                            Col = 1,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 22,
                            Col = 2,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 23,
                            Col = 3,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 24,
                            Col = 4,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 25,
                            Col = 5,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 26,
                            Col = 6,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 27,
                            Col = 7,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 28,
                            Col = 8,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 29,
                            Col = 9,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 30,
                            Col = 10,
                            Row = "C",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 31,
                            Col = 1,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 32,
                            Col = 2,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 33,
                            Col = 3,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 34,
                            Col = 4,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 35,
                            Col = 5,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 36,
                            Col = 6,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 37,
                            Col = 7,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 38,
                            Col = 8,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 39,
                            Col = 9,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 40,
                            Col = 10,
                            Row = "D",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 41,
                            Col = 1,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 42,
                            Col = 2,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 43,
                            Col = 3,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 44,
                            Col = 4,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 45,
                            Col = 5,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 46,
                            Col = 6,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 47,
                            Col = 7,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 48,
                            Col = 8,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 49,
                            Col = 9,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 50,
                            Col = 10,
                            Row = "E",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 51,
                            Col = 1,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 52,
                            Col = 2,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 53,
                            Col = 3,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 54,
                            Col = 4,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 55,
                            Col = 5,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 56,
                            Col = 6,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 57,
                            Col = 7,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 58,
                            Col = 8,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 59,
                            Col = 9,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 60,
                            Col = 10,
                            Row = "F",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 61,
                            Col = 1,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 62,
                            Col = 2,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 63,
                            Col = 3,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 64,
                            Col = 4,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 65,
                            Col = 5,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 66,
                            Col = 6,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 67,
                            Col = 7,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 68,
                            Col = 8,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 69,
                            Col = 9,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 70,
                            Col = 10,
                            Row = "G",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 71,
                            Col = 1,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 72,
                            Col = 2,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 73,
                            Col = 3,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 74,
                            Col = 4,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 75,
                            Col = 5,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 76,
                            Col = 6,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 77,
                            Col = 7,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 78,
                            Col = 8,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 79,
                            Col = 9,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 80,
                            Col = 10,
                            Row = "H",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 81,
                            Col = 1,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 82,
                            Col = 2,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 83,
                            Col = 3,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 84,
                            Col = 4,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 85,
                            Col = 5,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 86,
                            Col = 6,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 87,
                            Col = 7,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 88,
                            Col = 8,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 89,
                            Col = 9,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        },
                        new
                        {
                            Id = 90,
                            Col = 10,
                            Row = "I",
                            Status = 0,
                            UserName = ""
                        });
                });

            modelBuilder.Entity("Parkyou.Models.Report", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Id");

                    b.Property<bool>("Closed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Closed");

                    b.Property<string>("Col")
                        .HasColumnType("text")
                        .HasColumnName("Col");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime")
                        .HasColumnName("LastModified");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ReportedBy");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Resolution");

                    b.Property<string>("Row")
                        .HasColumnType("text")
                        .HasColumnName("Row");

                    b.Property<bool>("Solved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Solved");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("Parkyou.Models.Administrator", b =>
                {
                    b.HasBaseType("Parkyou.Models.ApplicationUser");

                    b.ToTable("administrators");

                    b.HasData(
                        new
                        {
                            Id = "5e2e7d09-328e-4219-bf70-be03f70a6e2c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "877761a2-3eea-4441-965d-740abd985da3",
                            Email = "vladulescualexandru1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "VLADULESCUALEXANDRU1@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEGkoJKEv7XkD6t07STWQOzJnTMMX9kigmNaTm2RcTKtp0THJWyUGTy9iQ5x6Bz+ahA==",
                            PhoneNumberConfirmed = false,
                            Rol = "Administrator",
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Parkyou.Models.User", b =>
                {
                    b.HasBaseType("Parkyou.Models.ApplicationUser");

                    b.Property<int?>("ParkSpotId")
                        .HasColumnType("int");

                    b.HasIndex("ParkSpotId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Parkyou.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Parkyou.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkyou.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Parkyou.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkyou.Models.Administrator", b =>
                {
                    b.HasOne("Parkyou.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Parkyou.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkyou.Models.User", b =>
                {
                    b.HasOne("Parkyou.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Parkyou.Models.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkyou.Models.ParkingSpot", "ParkSpot")
                        .WithMany()
                        .HasForeignKey("ParkSpotId");

                    b.Navigation("ParkSpot");
                });
#pragma warning restore 612, 618
        }
    }
}
